### ISSUE TITLE
Questions: Some questions regarding downlinks and different device classes

### ISSUE THREAD

**Issue by WillooWisp** [chirpstack/chirpstack#114]
Thanks for the good work with this awesome LoRa app server!

1) Is it possible to send downlinks with a common device profile supporting both class A and C devices?
I have a class A device, but I am unable to send downlinks to the device when using a device profile where "Device supports Class-C" is also checked. If I disable the Class C support on the profile it works. So is it required to always have a unique device profile per region and device class?

2) When sending downlinks to a class A device, it must send the data on the uplink port. Is this not handled by chirpstack? I would expect that I should be able to leave the FPort in the downlink unset and that chirpstack handles the port assignment automatically, but now it seems that I must wait for an uplink, then store that FPort, and then use that when I send downlinks, correct?

**Comment by brocaar** [comment]
In general, for asking questions, https://forum.chirpstack.io/ is a better place. Quick answers:

1. Yes, you need different device-profiles, because if Class-C is enabled, ChirpStack will send the downlink immediately to the device. If the device does not implement Class-C, then these downlinks are lost.
2. There is no relation to uplink fPort and downlink fPorts. This is application specific. E.g. uplink on port 10 might mean temperature reading, downlink on port 20 could mean change uplink interval setting. This is up to device vendors to implement as they like (within the fPort range that can be used, please refer to the LoRaWAN specs).
