### ISSUE TITLE
PostgreSQL SSL/TLS connections dont work

### ISSUE THREAD

**Issue by neilh2048** [chirpstack/chirpstack#156]
Hi

The dsn in the chirpstack.toml file doesnt connect over SSL/TLS connections, im trying to use sslmode=verify-full, this constantly fails, however using psql direct connection on the same machine with the same ssl mode connects successfully.

Chirpstack Journal reports
 `Error: Setup PostgreSQL connection pool error
 chirpstack[7480]: Caused by:
 chirpstack[7480]:     timed out waiting for connection: connection to server at "<ServerNAME>" (192.168.29.110), port 5432 failed: certificate could not be obtained: no SSL error reported
`
`dsn="postgres://chirpstack:PASSWORD@<ServerNAME>/chirpstack?sslmode=verify-full"` 
but this works
`psql -U chirpstack "sslmode=verify-full host=<ServerNAME> port=5432 dbname=chirpstack"`
with supplying the password on the command line connects as per below

ubuntu@chirpstack01:/etc/chirpstack$ netstat -an | grep EST
tcp        0      0 192.168.28.135:57286     192.168.29.110:5432      ESTABLISHED

Chirpstack host is Ubuntu 22.04, latest updates and newest version of chirpstack.

Thanks

Neil

**Comment by brocaar** [comment]
I have pushed a fix today to the `master` branch for this and it will be included in the next release. The issue was that some libraries were linked dynamically and some were not. The build platform was still using OpenSSL 1.1.1 where Ubuntu 22.04 is using OpenSSL 3.0.2 (which is a dependency of libpq, to which ChirpStack is dynamically linking). I believe this where your issue originates from.

I have completely refactored the way ChirpStack is cross-compiled. All external dependencies are now statically linked and this issue no longer occurs.
