### ISSUE TITLE
[Possible Bug] Hard Coded Code Rates

### ISSUE THREAD

**Issue by Grabt234** [chirpstack/chirpstack#225]
Hi

[This](https://forum.chirpstack.io/t/configuring-coderate-for-region-ism2400/15012) Chirpstack forum post describes an issue where the code rate appears to be hard coded.  I have run into the same issue.

When configuring Chirpstack (in a Docker containter) to communicate with the Semtech Packet forwarder, the code rate causes transmissions to be aborted. This prevents any communciations between a ISM2400 end device and Chirpstack.

**Comment by brocaar** [comment]
I believe this issue was already fixed: https://github.com/chirpstack/chirpstack/commit/e2214f94857bf3bfdbb8a981131a3eb9ccb8c5d5

See also:
https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/downlink/helpers.rs#L93

This is the rate that is used for ISM2400:
https://github.com/chirpstack/chirpstack/blob/master/lrwn/src/region/ism2400.rs#L31

**Comment by Grabt234** [comment]
Could not find a linked issue to that post, thank you for posting the relevant commits.
