### ISSUE TITLE
Minimizing resources and support of SQLite storage

### ISSUE THREAD

**Issue by momobel** [chirpstack/chirpstack#293]
## Context

We are looking to integrate Chirpstack in a lightweight embedded device that has the following characteristics:

- 1 ARM Cortex A7 core at 528MHz
- 256MB of RAM
- 256MB of NAND Flash storage

This device could be considered "quite low-end" compared to more recent devices such as Raspberry Pi 2 and above. As a result we need to minimize resources utilization: CPU, RAM, binary size and disk space. We would be happy to hear from you and discuss how to achieve this.

## Ideas

Technically, we thought about 2 possibilities with common point being reducing or changing dependencies. The first would be that Chirpstack supports SQLite storage as an option instead of Postgres, which should bring CPU, RAM and image size usage lower. The second would be changing Redis to something lighter such as KeyDB or optionally dropping external cache and caching in Chirpstack itself.

We are interested in contributing to Chirpstack such changes if they can be integrated:

- A. adding option to use SQLite instead of Postgres
- B. adding option to use in-memory "internal cache" instead of Redis

Of course, you may have additional ideas to minimize resources that we would be happy to hear and we are keen to contribute these as well.

## SQLite proof of concept

For information, we experimented SQLite option in this branch https://github.com/WattSense/chirpstack/tree/experiment_sqlite. It is in a mostly good state with a clean integration to select between postgres and sqlite and majority of changes working with both with almost same features.

There are a few exceptions though where some code is disabled for the sake of the proof of concept branch such as the search (SQL wasn't ported) and the row locking (not available in SQLite). These should be handled properly if the feature will be integrated upstream and same goes for an improvement of all commits with learning during this project.

The changes are mainly in `storage` module and seem to have a minimal impact on Chirpstack codebase overall, which is great!

Below is the state of the branch.

[x] Compiling binary and tests with both Postgres and SQLite
[x] Unit and integration tests with Postgres still passing
[x] Basic unit and integration tests (running them one by one) passing with SQLite (not passing when ran all at once)
[] Full unit tests passing with SQLite
[] Test in real scenario

What additional steps to the task list above are needed so the feature could be integrated?

## Where to go from there?

We are keen to contribute such changes to Chirpstack so the community and other users and companies, present or future could benefit from.
The big benefit is that Chirpstack could be ran on more IoT embedded devices, lighter, with less power consuption and usually more affordable. This could open up new opportunities for Chirpstack and open new doors for other projects and horizons.
Additionally, we could get involved in continuously contributing to Chirpstack to make it grow.

PS: As a side note, great that Chirpstack is now in Rust, we will be more likely to contribute!

**Comment by brocaar** [comment]
Thanks for raising this issue! I think it would be really interesting to support SQLite and I'm looking forward to review your changes. Please allow me some to to review these as **you did a lot of work** already!

With regards to the in-memory key/value storage, this has a lower priority. There are some features in Redis that ChirpStack uses which might not be available in in-memory Redis-like libraries. As the device-session data is also stored in Redis, this data must be persisted somehow.

> ... and the row locking (not available in SQLite). 

Maybe this is not an issue, as this is mostly to deal with multiple ChirpStack instances (e.g. scheduler loop). In case of SQLite, there would only be a single ChirpStack instance, so a row lock might not be needed (in all cases).

Thanks again and please give me some time to go through the changes you already have made.

**Comment by momobel** [comment]
Great that there is interest in SQLite support, looking forward to work on this together.

Also, thanks for taking the time to look at the work. Meanwhile, I went through the commits again and add below other todo items from the top of my head:

- Use single SQLite DB setup with latest ChirpStack expected schema and remove other ones
- Clean SQLite/Postgres selection and instantiation
- Rework commits to drop unsuccessful ones and adapt some to more efficient ways of doing
- Document how to generate schema_sqlite.rs

I remain available if you have any remark or questions.

**Comment by brocaar** [comment]
Hi @momobel over the past weeks I've been thinking about this a lot. For the sake of reducing complexity, I think putting the backend choice behind a feature flag is a good idea. Thus either PostgreSQL or SQLite, not both (at least not for now).

Looking at your changes, I think it can be summarized to:

* Implementing two schemas (PostgreSQL / SQLite)
* Implementing SQL migrations for both databases
* Wrapping types that can not be used with SQLite into a type that uses the native PostgreSQL type or falls back to something supported by SQLite (e.g. JSON type using a text field in case of SQLite)
* Fixing some queries to make these either compatible with both or based on feature flag use a database specific query

In general, I think this is something that could be merged into the main repository eventually as long as it doesn't limit the PostgreSQL support in any way. With that regards howver, I do see one blocker (at least at the moment).

Currently all DB queries are using `tokio::task::spawn_blocking(...)` as queries performed using Diesel are blocking. During the ChirpStack v3 > v4 migration I have considered other DB frameworks that did implement `async` / `await` but Diesel turned out the solution that I found the most elegant.

Since then work has been done (by the Diesel author) to also support `async`:
https://github.com/weiznich/diesel_async

However, this is currently only supporting PostgeSQL and MySQL. In that repository, you will find a request to also add SQLite support (https://github.com/weiznich/diesel_async/discussions/95), but currently it is not supported and I'm not sure if somebody is working on this right now to add support for this.

---

For me implementing `diesel_async` has a higher prio than implementing SQLite support because:

* `diesel_async` uses `tokio-postgres` which is a pure-Rust PostgreSQL client, where `pq-sys` wraps the PostgreSQL client library which is written in C. Moving to a pure-Rust implementation makes the cross-compilation a lot easier:
  * We no longer have to cross-compile the PostgreSQL client library (C) for all targets
  * Where the PostgreSQL client library in C has a dependency on OpenSSL, the `tokio-postgres` crate could use the `rustls` crate for TLS, which is also pure-Rust. Eventually this would make it possible to completely migrate away from using OpenSSL and the need to cross-compile OpenSSL for all targets.
* We can cleanup all the `tokio::task::spawn_blocking(...)` blocks

I do remain interested in supporting SQLite, since I do see an use-case for this. However priority-wise (for me), I would like to address the above first before spending time on SQLite support. Hopefully by then `diesel_async` will also have SQLite support :-) Hopefully this makes sense to you.

**Comment by momobel** [comment]
Hey @brocaar, thanks for the followup.

To be honest it is a bit unexpected but I understand the reasoning so let's try to find a way forward!

I understand moving to diesel_async is important to you, is this something that you already planned for or that you expect contributors to do? What timeline do you have in mind?
diesel_async maintainer doesn't plan to add sqlite so I will at least study how to contribute it.

That topic aside and looking at the global picture, the overall work would be the following:

* A. Move to diesel_async instead of diesel
* B. Support sqlite in diesel_async
* C. Add sqlite support in Chirpstack

Now, considering A and B will be progressing and focusing on the end goal of sqlite support: some changes I did do not depend on sqlite support. They would still prepare the terrain for the future work, I am mainly thinking about the type wrapping here. 
What do you think about creating a PR for this part? This would greatly help splitting the work in multiple iterations.

**Comment by brocaar** [comment]
For the `diesel_async` refactor, please see:
https://github.com/chirpstack/chirpstack/tree/feature/diesel_async

This work is almost complete, after which I will merge it into the `master` branch.

I will create a `feature/sqlite_support` branch once the above has been merged. Then we can use that to add the SQLite support in multiple iterations. Sounds good?

**Comment by momobel** [comment]
Looks like a good plan. Thanks!

**Comment by brocaar** [comment]
@momobel I have just merged the async diesel work into `master` and I have created the following branch to use for the SQLite feature: https://github.com/chirpstack/chirpstack/tree/feat_sqlite_support.

**Comment by momobel** [comment]
Hi @brocaar, just to let you know, I have still this in mind and am trying to workout a solution with diesel_async maintainer.
I keep you updated and start PRs on the branch as soon as it's clearer.

**Comment by brocaar** [comment]
Thanks for the update :+1:

**Comment by brocaar** [comment]
I'm closing this issue as all the work has been merged into the master branch.
