### ISSUE TITLE
DevAddr recycling causing extreme performance load

### ISSUE THREAD

**Issue by stefandxm** [chirpstack/chirpstack#362]
### How I found it

We just got a batch of really shitty LoRaWAN devices, their P-O-* software make them re-join all the time and this causes Chirpstack to not-be-so-happy.

While profiling redis i realized that chirpstack was asking more than 1 time per second about dev info on a device that hasnt been active for several hours. And it kept asking, and kept asking, and kept asking. Redis then consumes close to 100%, chirpstack consumes cores*100% CPU. Redis is hitting hundred of millions request per minutes but at the same the mqtt broker shows there is only coming a few thousands of messages during the same time-span.

So I set up a UDP-relayer and ran an instance on my developer computer to figure out what was going on, I had spotted the redis query coming from `device_session.rs / get` since before so I set a 'smart' break point there and and boom, I got a stack trace.

The stack trace tells me that it originates from looking up deveui from devaddr, in my particular incident it originated from `get_for_phypayload_and_incr_f_cnt_up` (`data.rs`). Where it looks from what deveuis may be associated with the devaddr, it gets *a lot* of them and it then starts looping them, calling `device_session::get()`. 

_This is why redis was asking for a device that has been inactive for hours.._

### What I think may be the issue and how it can be mitigated

I believe the the shitty devices we got in our network has caused the DevAddr's to be recycled, and not just once but several hundred of times. But there is no explicit business logic removing the old devaddr->deveui entries that I can find, I am guessing it uses auto-expiration with TTL.

I am no Rust expert, it took me half an hour to figure out how to get the debugger to launch and many more minutes to create some simple if statements. So i add my 'maybe this could work'-code in this post since I doubt it has code quality enough for a PR.

### Known issues with the "code"

* Not tested *at all*, think about it as pseudo-code
* Known issues with error handling (see comment in code)
* Existing populated lists will not be fixed with this code, this code will only attempt to make it not happen again, not to fix existing data sets
* It needs to be verified that this wont break for any other logic in the application that I am not aware of

#### The code
device_session.rs function save() (line 28 in 4.6.0 branch):
```
    // after let mut remove_old_addr = false;
    //
    // Warning; No handling/checks if the curr_session is null 
    // or if some kind of error was raised by self::get() ??
    let curr_session : chirpstack_api::internal::DeviceSession = self::get(&eui).await?;
    let old_addr_key_parsed = DevAddr::from_slice(&curr_session.dev_addr)?;
    if old_addr_key_parsed != addr
    {
        remove_old_addr = true;
    }
```

device_session.rs function save() - inside the spawn_blocking lambda (line 46 in 4.6.0 branch):
```
            // after let mut c = get_redis_conn()?;
            if remove_old_addr 
            {
                let old_addr_key = redis_key(format!("devaddr:{{{}}}", old_addr_key_parsed));
                c.new_pipeline()
                .atomic()
                .cmd("SREM")
                .arg(&old_addr_key)
                .arg(&eui.to_be_bytes())                
                .ignore()
                .query(&mut c)?;
            }
```

**Comment by stefandxm** [comment]
We are working on fixing a clean-up job for any build-ups. If there are more users experiencing the same issue we have it would be good if you made a shout so we know if the utility/code should be published.

**Comment by brocaar** [comment]
Hi @stefandxm, thanks for letting me know about this issue. I understand the issue and what your code is doing:

Before saving a (new) device-session, it queries the DB to see if there is already a device-session for that DevEUI, then if the DevAddr != new device-session DevAddr, it removes the DevEUI from the DevAddr => [DevEUI] set in Redis.

However, I'm not sure if this is the best way to approach this problem as each save would then require two DB queries instead of one. While one additional query doesn't sound much, it could have quite some performance impact under high load e.g. see: https://github.com/chirpstack/chirpstack/commit/b65faf7b980fa78f4143f00f6d75752567d8463a.

On the other hand, this is something that must be fixed as a bad-behaving device could cause a higher DB load.

Let me think about how this issue could be approached in an other way.

**Comment by manjunathgitbub** [comment]
Hi@brocaar, I'm currently moved from chirpstack-api version 3.12.4 to chirpstack-api 4.6.0 version  facing an Issue: **'GatewayServiceStub' object has no attribute 'StreamFrameLogs'**  and for this 
#Construct request using is
req = api.StreamGatewayFrameLogsRequest()

When I checked in the api lib of gateway the above methods and constructs are deprecated.
OLD CHIRPSTACK API LIB
https://github.com/brocaar/chirpstack-api/blob/master/python/src/chirpstack_api/as_pb/external/api/gateway_pb2_grpc.py
https://github.com/brocaar/chirpstack-api/blob/master/python/src/chirpstack_api/as_pb/external/api/gateway_pb2.py

NEW 4.6.0 CHIRPSTACK API LIB
https://github.com/chirpstack/chirpstack/blob/master/api/python/src/chirpstack_api/api/gateway_pb2.py
https://github.com/chirpstack/chirpstack/blob/master/api/python/src/chirpstack_api/api/gateway_pb2_grpc.py

Can you give pointers to resolve this dependency!!
Thanks in advance.

**Comment by bconway** [comment]
> Hi@brocaar, I'm currently moved from chirpstack-api version 3.12.4 to chirpstack-api 4.6.0 version facing an Issue: from chirpstack_api import api client = api.GatewayServiceStub(channel) auth_token = [("authorization", "Bearer %s" % api_token)] req = api.StreamGatewayFramesRequest() req.gateway_id = id frame_stream = client.StreamFrameLogs(req,metadata=auth_token) (Pdb) n **AttributeError: 'GatewayServiceStub' object has no attribute 'StreamFrameLogs'**

I don't think your comment pertains to this issue. Try the ChirpStack forum for support:

https://forum.chirpstack.io/

**Comment by manjunathgitbub** [comment]
Hi Bconway, Sure will post on chirpstack forum.

**Comment by stefandxm** [comment]
I am not sure how we can test this out-side of production without interfering with our online-fleet.
I can have a look at it and see if we can reproduce it with any of them simulators out there but it will require us a few weeks since there are school holidays here at the moment.

I/We are very happy to see you are spending time on it so we will assist in any way we can.

BR Stefan

**Comment by brocaar** [comment]
@stefandxm I just did a simple test (simulation with 2000 devices for 5 minutes incl OTAA, sending every 5 seconds = 400 device uplinks per sec x 3 gateways = 1200 uplinks / sec before de-duplication):

NetID 000000:

* DS in Redis: 777_047 PostgreSQL + 2_605_092 Redis queries
* DS in PostgreSQL: 989_450 PostgreSQL + 1_864_200 Redis queries

NetID FE0000:

* DS in Redis: 778_950 PostgreSQL + 4_222_712 Redis queries
* DS in PostgreSQL: 987_178 PostgreSQL + 1_860_154 Redis queries


(note that the number of queries are since the start of the `chirpstack` service and thus includes the provisioning of devices as well).

---

As you can see, with the device-sessions in Redis there is a significant increase between NetID 000000 vs FE0000. With the device-sessions in PostgreSQL the number of queries stays constant.

**Comment by brocaar** [comment]
Please see: https://forum.chirpstack.io/t/release-chirpstack-v4-7-test-releases/19093

**Comment by stefandxm** [comment]
Did you change the DevAddr space ? I think that is the main culprit

**Comment by stefandxm** [comment]
(We want to test patch but because of the old issue we moved redis and chirpstack to another physical server, so if the issue is moved to postgres load we will have to emergency move postgresql)

**Comment by stefandxm** [comment]
And we are running today around 9000 units with OTAA. The really shitty ones are around 6000 :(

**Comment by brocaar** [comment]
Please note that the 4.7 release also contains improvements on the
PostgreSQL side. Before assuming you need to scale up PostgreSQL, I would
do some testing first.
