### ISSUE TITLE
MQTT v5 required?

### ISSUE THREAD

**Issue by abalmos** [chirpstack/chirpstack#407]
Hi @brocaar, thank you for this amazing product! We use it as a primary data collection tool for our research. We have enjoyed it a lot.

Quick question: Does 4.7 introduce a requirement for MQTT 5?  We use NATS as our primary message queue server, and it only emulates MQTT 3.1.1. That has worked fine from v3 and up to v4.6 and prior, but with 4.7 chirpstack gets stuck in a (very) tight loop trying to connect to the MQTT server. NATS closes the connection because it does not support MQTT version 5.

Thanks!

**Comment by zzakir** [comment]
@brocaar I am facing the same issue. When we tried upgrading to Chirpstack version 4.7, it is not able to establish connection to our MQTT broker which does not support MQTT version 5. 

I can see in the changelog that you are using rumqttc client instead of Paho now. rumqttc supports both MQTT 3.1.1 and MQTT 5. But Chirpstack somehow only supports MQTT 5 from rumqttc.

Upgrading to MQTT 5 is a big change for us. Will it be possible to add support to MQTT 3.1.1 as rumqttc already supports it?

**Comment by zzakir** [comment]
I can see this in the file chirpstack/src/integration/mqtt.rs

`use rumqttc::tokio_rustls::rustls;
use rumqttc::v5::mqttbytes::v5::{ConnectReturnCode, Publish};
use rumqttc::v5::{mqttbytes::QoS, AsyncClient, Event, Incoming, MqttOptions};
use rumqttc::Transport;`

This means that chirpstack now supports only MQTT v5.

**Comment by zzakir** [comment]
I saw this forum thread where you explain your reasoning behind this and it makes sense now.

https://forum.chirpstack.io/t/chirpstack-4-7-0-mqtt-v3-support/18508/7

If it is possible please update the chagelog in the website to reflect this, as many users might walk into it blindly thinking that 
MQTT v3 is still supported.

**Comment by brocaar** [comment]
@zzakir I have updated the changelog with a MQTTv5 requirement note.

I'm closing this issue, because yes MQTTv5 is a requirement.

**Comment by abalmos** [comment]
That is unfortunate, but thank you very much for clarifying.
