### ISSUE TITLE
Logout when try access to device

### ISSUE THREAD

**Issue by ocin-niko** [chirpstack/chirpstack#415]
Hello everyone,

I’m encountering an error with ChirpStack that states ‘Panicked at chirpstack/scr/storage/metrics.rs:239:30’. Additionally, I’m experiencing an issue where the system logs me out when I try to access a registered device. I have attached an image of the application log for reference.

![aa1604cc116d7edc2b32713fad724f9e01d1cfc0](https://github.com/chirpstack/chirpstack/assets/16289547/7c03f501-051f-4d3e-b211-c8ad49d367f2)

My current version is 4.6.0

that problem occurs everytime when I try to access a any registered device.

**Comment by brocaar** [comment]
A few questions:

* What is your timezone name (e.g. Europe/Amsterdam) (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)?
* Was there a daylight saving change in the date range from your error?

**Comment by ocin-niko** [comment]
No problem.

- America/Santiago.

- Yes, there was, but I don't know how long the error occurred, since I only connected through MQTT, when we wanted to see something more specific through the GUI we realized the error

**Comment by ocin-niko** [comment]
I confirm that on April 6 here in Chile there was a daylight saving

**Comment by brocaar** [comment]
I can confirm there is an issue. ChirpStack tries to truncate the timestamp based on the aggregation level (in your case it truncates it to midnight for each day). In Europe we have the same, but the DST change is not at midnight, in your case it is. Therefore some timestamps (e.g. 2024-04-07 00:00:00) are ambiguous because they happen twice in time.

I need to think about the best way to deal with this.
