### ISSUE TITLE
Parse true/false as 1/0 on device metrics

### ISSUE THREAD

**Issue by lawrencedudley** [chirpstack/chirpstack#45]
There's quite a lot of codecs that exist in the TTN repository (pulling this in is lovely by the way, great work) that return true/false values.

It would be lovely if these could be graphed as 1/0 on the device metrics page that's new in v4 as it would be useful to track a binary state over time.

**Comment by brocaar** [comment]
Please note that you should already be able to graph these, but then as true / false text.

**Comment by lawrencedudley** [comment]
Boolean/string just shows as one (latest) metric rather than as a graph for me... I might be confused!
<img width="1757" alt="Screenshot 2022-09-28 at 13 20 23" src="https://user-images.githubusercontent.com/272317/192777141-456eb61e-5354-4b8b-b0f8-ec234456d408.png">

**Comment by brocaar** [comment]
Do you have an example how you would like to display this value as graph and how this data would be aggregated (last hour / day / month)?

**Comment by brocaar** [comment]
But how would the true (1) / false (0) value be aggregated? Note that there is a single data-point stored per hour, day and month.

For a gauge values, the average is calculated over all measurements
For counter values, only the last value is stored
For absolute values, the sum is calculated over all values

How would you aggregate binary true (1) / false (1) value? Would the output be the percentage of true and false (together always 100%)?

**Comment by brocaar** [comment]
So that could be a bar or line graph, where per hour (or per day or month) you have a true and a false bar or line showing the number of reported states. Still I'm not sure if that is very useful. E.g. in case of a parking sensor you probably want to capture how long it was true and false so that you can calculate the percentage of time it was occupied within that hour.

If the device only sends an event on state change, then you would not be able to capture this data from the graph. E.g. the car parks at 16:01 and leaves at 16:57. So the graph shows for that hour: true: 1, false: 1 (either two bars or two lines).

If the device would send its state periodically, it would be more easy. But then a percentage would make more sense. E.g. the parking spot was 75% occupied within that hour.

This could be a tricky one, as there are many different cases where a bool is used.

**Comment by lawrencedudley** [comment]
Yeah I can see what you mean! I'm gonna close this as it clearly needs more thought and I'm sure there are higher-priority items at the moment.
