### ISSUE TITLE
Dismatching device coderate

### ISSUE THREAD

**Issue by sergorl** [chirpstack/chirpstack#51]
Dear [@brocaar](https://forum.chirpstack.io/u/brocaar), I see in chirpstack v4 [chirpstack/chirpstack/src/downlink/helpers.rs](https://github.com/chirpstack/chirpstack/blob/f27b8da38dc772d74d40309154d9d423c33b55ab/chirpstack/src/downlink/helpers.rs), here only `chirpstack_api::gw::CodeRate::Cr45.into()` is used for all devices despite their requested coderate:

```rust
pub fn set_tx_info_data_rate(
    tx_info: &mut chirpstack_api::gw::DownlinkTxInfo,
    dr: &DataRateModulation,
) -> Result<()> {
    match dr {
        DataRateModulation::Lora(v) => {
            tx_info.modulation = Some(gw::Modulation {
                parameters: Some(gw::modulation::Parameters::Lora(gw::LoraModulationInfo {
                    bandwidth: v.bandwidth,
                    spreading_factor: v.spreading_factor as u32,
                    code_rate: chirpstack_api::gw::CodeRate::Cr45.into(),
                    polarization_inversion: true,
                    code_rate_legacy: "".into(),
                })),
            });
        }
        DataRateModulation::Fsk(v) => {
            tx_info.modulation = Some(gw::Modulation {
                parameters: Some(gw::modulation::Parameters::Fsk(gw::FskModulationInfo {
                    datarate: v.bitrate,
                    frequency_deviation: v.bitrate / 2, // see: https://github.com/brocaar/chirpstack-gateway-bridge/issues/16
                })),
            });
        }
        DataRateModulation::LrFhss(_) => {
            return Err(anyhow!("LR-FHSS is not supported for downlink"));
        }
    }

    Ok(())
}
```

I believe that’s why I face this warning in my packet-forwarder:

[chirpstack forum](https://forum.chirpstack.io/t/configuring-coderate-for-region-ism2400/15012)

and I believe that’s why I face infinite loop of `Join Request` from my device `ISM2400`.

P.S.: In my opinion this behaviour is wrong, since device may have different coderates  - not only `4/5`

**Comment by brocaar** [comment]
Actually, excluding 2.4 GHz devices (which are not part of the LoRa Alliance specs), all devices should use `4/5` as coding rate when using LoRa modulation:

![image](https://user-images.githubusercontent.com/165497/196739334-5b024846-ea0c-4409-9278-bce45f016e1e.png)

I will look into this for 2.4GHz, it might be different.

**Comment by brocaar** [comment]
Update: If using the ChirpStack Gateway OS (which uses the Concentratord instead of the UDP packet-forwarder), the downlinks are working fine with coding-rate "4/5". I did notice that the 2.4 GHz UDP packet-forwarder only accepts "4/8LI" as downlink coding-rate (https://github.com/Lora-net/gateway_2g4_hal/blob/master/packet_forwarder/src/lora_pkt_fwd.c#L1686), however "4/5" is a valid coding-rate in the HAL (https://github.com/Lora-net/gateway_2g4_hal/blob/master/libloragw/inc/loragw_hal.h#L74).

Nothing in the ISM2400 proposal states that downlinks must use "4/8LI" as downlink coding-rate. I have asked Semtech if they can confirm the correct downlink coding-rate for ISM2400 and also if they could make this explicit in the ISM2400 document.

**Comment by brocaar** [comment]
I just got the confirmation that 2.4 GHz must indeed use "4/8LI" as downlink coding-rate. This means that we need to add the LoRa coding-date to each region configuration (or `DataRateModulation`). I will look into this soon.

**Comment by brocaar** [comment]
The above commit fixes this issue.
