### ISSUE TITLE
MQTT Integration - support last will and testament

### ISSUE THREAD

**Issue by rmay-intwine** [chirpstack/chirpstack#538]
It would be great if the MQTT integration allowed an optional last will and testament to be configured. This would allow the MQTT broker that the Chirpstack is integrated with to know when the stack has gone offline. This is particularly important for cases when Chirpstack is on a separate device from the broker.

The underlying library, rumqttc, supports this functionality [0] so it should be a matter of reading the parameter and specifying the last will object in [1].

[0] https://docs.rs/rumqttc/latest/rumqttc/mqttbytes/v4/struct.LastWill.html
[1] https://github.com/chirpstack/chirpstack/blob/20ec2877f24aacfeb0582eb53af184cea5359b11/chirpstack/src/integration/mqtt.rs

**Comment by brocaar** [comment]
The Last Will and Testament is already used by the ChirpStack MQTT Forwarder to detect the status of a gateway. E.g. there is a retained `eu868/gateway/0102030405060708/state/conn` message that contains ONLINE or OFFLINE status. On connect it is set to ONLINE and in the Last Will and Testament a message with OFFLINE is published (both as retained).

Since ChirpStack can be deployed as a cluster, how would you see this working in case of ChirpStack? A single topic would not work because there could be N ChirpStack instances and they should not publish to the same topic because you want to be warned when all instances are down, not when a single is down (e.g. Kubernetes might restart a pod on a different node of the Kubernetes cluster).

**Comment by rmay-intwine** [comment]
Apologies if I wasn't clear, but I was referring to the MQTT Integration, not the MQTT Forwarder.

**Comment by brocaar** [comment]
Sorry, what I mean is that the Last Will and Testament is already used at other places within ChirpStack. More specific: Chirpstack MQTT Forwarder. This implementation of the LWT is easy because the message represents a single entity; the gateway thus it can publish the LWT on a MQTT topic that is tied to the Gateway ID. If the LWT is triggered you know the gateway is down.

This is not the case with the Chirpstack MQTT integration. There can be multiple instances when ChirpStack is running as a cluster. If the LWT is triggered in this case, you don't know if your cluster is down or if for example Kubernetes is respawning a pod on an other node of the Kubernetes cluster.

So I'm not sure if this would be a helpful feature to add to the MQTT integration because the LWT message will never give you the information if your cluster is healthy or not. I think it would be better to use the Prometheus metrics that are already available for monitoring. That will give you the information of uplinks / downlinks processed by the cluster. If that number suddenly goes to `0` you know there is an issue.

**Comment by rmay-intwine** [comment]
Interesting, I hadn't considered the problem of a cluster of Chirpstacks. I will find a different way to implement what I'm looking for.  Thanks!
