### ISSUE TITLE
Sensors communication lost

### ISSUE THREAD

**Issue by sirvincent** [chirpstack/chirpstack#557]
A few weeks ago all of our sensors simultaneously lost  connection to ChirpStack. 
Since it is a few weeks ago we do not have the log files anymore. However at that time we couldn't see anything strange in the logs. It is the second time in a few years that suddenly communication to all sensors simultaneously is lost.
ChirpStack & gateway operate normally without any errors. We have frame-counter validation disabled.
Manual reconnecting each sensor brings back communication, however we have hundreds of sensors of which some are very hard to reach thus manual steps are hard to do. 

Since this issue contains limited information about the problem we are globally wondering if there is anything in ChirpStack that for longer duration (years) can give problems? For example a type that overflows.

We now run chirpstack version 4.9.0

**Comment by brocaar** [comment]
> We have frame-counter validation disabled

In general this is not a good idea because it compromises security. A replay attack could easily cause such scenario you are describing. Note that only the lower 16 bits of the FCnt are sent, the 16 MSB are automatically derrived based on rollover of the 16 bit FCnt value. A replay could automatically reset the 16 MSB bit (as it looks like the device has been reset after a replay attack) after which the device stops working.

>  we are globally wondering if there is anything in ChirpStack that for longer duration (years) can give problem

There is nothing I can think of right now. In the past the Redis device-session TTL could have been an issue (after long inactivity), but with the device-session migration to PostgreSQL this is no longer the case.

> Manual reconnecting each sensor brings back communication

Do you mean a new OTAA join?

**Comment by sirvincent** [comment]
Thanks for the quick reply!

Regarding security that is good to know that those symptoms can be the same!
I only just see that some sensors of which the connection lost do have frame counter validation enabled.
For the sensors who have it disabled, we will enable frame counter validation.

Good to read about PostgreSQL.

> Do you mean a new OTAA join?

 Yes

**Comment by brocaar** [comment]
Per LoRaWAN spec. frame-counters are 32 bit (very old devices might use 16 bit).
