### ISSUE TITLE
Implement Azure IoT Hub GW <> NS backend

### ISSUE THREAD

**Issue by brocaar** [chirpstack/chirpstack#7]

**Comment by mogaleaf** [comment]
Good morning @brocaar, I would like to try working on this one as I need it for a PoC.
Is it fine by you ?
What did you have in mind?

So far what I have seen is : 
- There is no sdk provided in Rust to connect Azure.
- AMQP protocol could be used to connect a Service Bus Namespace, however the support of partition may be tricky 
- If we use the Event hub instead of the bus we can use a Kafka client to fetch the telemetry (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview)

So I was thinking of using an Event hub and the kafka client (found the idea here https://www.adrians-blog.com/articles/software/2021/12/08/azure-eventhubs-in-rust/ )
And you are already using the dependency.

I think I would also need to change the gateway-bridge to send information about the region as well.

Thanks

**Comment by brocaar** [comment]
I'm still in the development of this, but I'm planning to add a Redis based gateway backend (next to the MQTT). Using Redis Streams we have buffering + it makes it possible to use any language to integrate with this (and thus we can use the Go SDK).

**Comment by mogaleaf** [comment]
Do you mean telemetry will be sent over redis in replacement of mqtt or two connections one for telemetry over mqtt and one for config like region ?

**Comment by brocaar** [comment]
It would be something like (Redis Stream):

`[ChirpStack Gateway Bridge] <- MQTT -> [IoT Hub] <- Service Bus -> [ChirpStack Azure Bridge] <- Redis Streams -> [ChirpStack]`

Or (MQTT):

`[ChirpStack Gateway Bridge] <- MQTT -> [IoT Hub] <- Service Bus -> [ChirpStack Azure Bridge] <- MQTT -> [ChirpStack]`

After thinking about this a bit longer, maybe going the MQTT route is simpler + it makes the debugging easier as you can subscribe to the gateway MQTT topics directly to see what is going on. Depending the MQTT broker you use, it should not be a bottleneck.

I might start working on this too in the next couple of days, as I would like to get support for the Azure IoT Hub resolved for some clients :-) Originally I was planning to start working on the GCP IoT Hub first (#6), but they are deprecating the GCP IoT Hub.

**Comment by mogaleaf** [comment]
Thanks for the explanation.

I have a better understanding. The downside I see it that you still need to host a Mqtt somewhere with this architecture. It can be a lot of overhead for some small companies like us :)

However I understand because the integration directly with the azure system is not easy with rust.

Because we needed to validate we could do it here is the POC I have done : 
https://github.com/mogaleaf/chirpstack/pull/1

it comes along with a none breaking change in the gateway bridge to get the region : 

https://github.com/mogaleaf/chirpstack-gateway-bridge/pull/1

I'm still waiting on a review from one person of my team for chirpstack and was planning to open a PR afterward.

I have used the kafka client to stream (from the EventGrid, not the routing) and the amqp client to push frames.

It's my first development with Rust so probably a bit messy but I have managed to done some tests and it works so far.

Indeed gcp is out that's why we are looking for option...

**Comment by bas-hiber** [comment]
@mogaleaf This looks great, something like this would really help us out

**Comment by brocaar** [comment]
Not bad for a first Rust project :+1: 

> I have a better understanding. The downside I see it that you still need to host a Mqtt somewhere with this architecture. It can be a lot of overhead for some small companies like us :)

Depending your needs, you have a MQTT broker up and running with an `apt install mosquitto`. But you are correct that it requires an additional component in-between which can be an advantage or disadvantage. It can be an advantage if you want to migrate from or to Azure IoT Hub, as you can also connect your gateways directly over MQTT. The other advantage is that it keeps the dependencies of each backend out of the ChirpStack project (some SDKs pull in a lot of dependencies).

> it comes along with a none breaking change in the gateway bridge to get the region :

Not sure if that would be needed? I would imagine a single IoT Hub per region. Each region configuration in ChirpStack has already its own region name configured.

**Comment by mogaleaf** [comment]
Thanks, I think you re totally right, no need to have the region in the gateway, I guess either one hub per region or on event queue based on other properties.

I'll make this change.

For the change of architecture (having a Chirpstack Azure Bridge), the other downside I see is that you have to make it scale and redundancy  (the mqtt) and also configure the security around it. While azure bridge already provides all of those features. You basically go to two queues before reading the frame. For us for instance it would be too much of a burden as we are a very small team.

thanks again

**Comment by brocaar** [comment]
Which is why initially I was thinking about a Redis based backend, as Redis is already a requirement to setup ChirpStack.

Let me gather some more feedback from other companies I'm working with and that are using the Azure IoT Hub.

**Comment by brocaar** [comment]
I'm closing this issue as currently this is not high on my list of priorities currently.
