### ISSUE TITLE
Tenant user rights

### ISSUE THREAD

**Issue by samimk** [chirpstack/chirpstack#71]
Platform: Chirpstack 4 on Docker, OpenSUSE 15.4.

When an unprivileged user logs in, Add gateway, Delete gateway, Delete device buttons are enabled. After clicking on any of these buttons, the user is logged out.

**Comment by brocaar** [comment]
I'm not sure if I can reproduce all cases:

Steps I tried:

* I created an active / non-admin user
* I added this user to the default tenant, without any admin rights

I do not see add gateway or delete gateway buttons. I do see the delete device button, which on click redirects to login (because of auth error of the API). The issue was a missing <Admin> block around this component, checking if the user was authorized to perform this action and if not, hide the button.
